<?php
declare(strict_types=1);

namespace OCA\Learning\Tests\Unit\Service;

use OCA\Learning\Db\Certificate;
use OCA\Learning\Db\CertificateMapper;
use OCA\Learning\Db\UserTelosMapper;
use OCA\Learning\Service\BadgeService;
use OCA\Learning\Service\DataExportService;
use OCA\Learning\Service\StreakService;
use OCA\Learning\Service\XpService;
use OCA\Learning\Tests\Support\FakeDbConnection;
use PHPUnit\Framework\TestCase;

/**
 * DSGVO-02: DataExportService::exportForUser() Art.20 certificates block contract.
 *
 * Wave-0 RED suite — both tests fail against the skeleton ('certificates' => []).
 * They flip GREEN in 163-04 when the real CertificateMapper query is wired in.
 *
 * Design notes:
 * - FakeDbConnection (from FakeInfrastructure) handles all QB calls generated by
 *   exportForUser's other branches (leitner_items, sessions, answers, pools, courses,
 *   campaign_progress, kudos) — it absorbs innerJoin/leftJoin/groupBy via FakeQueryBuilder.
 * - BadgeService stub (PhpUnitStubs) has only checkAndAward; getUserBadges is added as a
 *   virtual method via addMethods(). Flagged for 163-01 to add to the stub if needed by
 *   other tests.
 * - CertificateMapper is autoloaded from the real class; mock intercepts findByUserId
 *   without executing the DB query (constructor disabled by createMock).
 */
class DataExportServiceTest extends TestCase {

    private const USER = 'alice';
    private const COURSE_ID = 42;
    private const VERIFICATION_ID = 'vc-abc-001';
    private const ISSUED_AT = 1700000000;
    private const CREDENTIAL_JWT = 'eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.stub.sig';

    private function makeCertificate(): Certificate {
        $cert = new Certificate();
        $cert->setVerificationId(self::VERIFICATION_ID);
        $cert->setUserId(self::USER);
        $cert->setCourseId(self::COURSE_ID);
        $cert->setIssuedAt(self::ISSUED_AT);
        $cert->setExpiresAt(null);
        $cert->setRevoked(false);
        $cert->setCredentialJson(self::CREDENTIAL_JWT);
        return $cert;
    }

    /**
     * Build DataExportService with injectable dependencies.
     *
     * @param Certificate[] $certs  what CertificateMapper::findByUserId returns
     */
    private function makeService(array $certs): DataExportService {
        $certMapper = $this->createMock(CertificateMapper::class);
        $certMapper->method('findByUserId')->willReturn($certs);

        // PhpUnitStubs BadgeService lacks getUserBadges — add as virtual method.
        // Note for 163-01: consider adding getUserBadges(): array to the stub.
        $badgeService = $this->getMockBuilder(BadgeService::class)
            ->disableOriginalConstructor()
            ->addMethods(['getUserBadges'])
            ->getMock();
        $badgeService->method('getUserBadges')->willReturn([]);

        $userTelosMapper = $this->createMock(UserTelosMapper::class);
        $userTelosMapper->method('findByUserIdOrNull')->willReturn(null);

        $xpService = $this->createMock(XpService::class);
        $xpService->method('calculateXp')->willReturn(['total_xp' => 0, 'level' => 1]);

        $streakService = $this->createMock(StreakService::class);
        $streakService->method('getStreak')->willReturn(['current_streak' => 0]);

        return new DataExportService(
            // FakeDbConnection absorbs all QB calls from leitner_items/sessions/answers/pools/
            // courses/campaign_progress/kudos branches (innerJoin, leftJoin, groupBy all handled).
            new FakeDbConnection(),
            $userTelosMapper,
            $xpService,
            $streakService,
            $badgeService,
            $certMapper,
        );
    }

    /**
     * DSGVO-02: exportForUser() must include a 'certificates' block with at least one entry
     * carrying verification_id, course_id, issued_at, expires_at, revoked, and the raw
     * VC-JWT in credential_jwt.
     *
     * RED at Wave 0: skeleton returns 'certificates' => [] — assertNotEmpty fails with
     * message "certificates block must not be empty when user holds a certificate".
     * GREEN after 163-04 calls certificateMapper->findByUserId() and maps the results.
     */
    public function testExportIncludesCertificates(): void {
        $svc = $this->makeService([$this->makeCertificate()]);
        $result = $svc->exportForUser(self::USER);

        $this->assertArrayHasKey('certificates', $result,
            'exportForUser() must include a certificates key');
        $this->assertNotEmpty($result['certificates'],
            'certificates block must not be empty when user holds a certificate');

        $entry = $result['certificates'][0];
        $this->assertArrayHasKey('verification_id', $entry);
        $this->assertArrayHasKey('course_id', $entry);
        $this->assertArrayHasKey('issued_at', $entry);
        $this->assertArrayHasKey('expires_at', $entry);
        $this->assertArrayHasKey('revoked', $entry);
        $this->assertArrayHasKey('credential_jwt', $entry,
            'Art.20 DSGVO: full VC-JWT must be included in own-data export');
    }

    /**
     * DSGVO-02: the exported certificate must carry the caller's OWN full VC-JWT —
     * not a cross-user pseudonym projection or a stripped-down version. The credential_jwt
     * field must match what CertificateMapper::getCredentialJson() returns verbatim.
     *
     * RED at Wave 0: certificates block is empty — assertSame on entry[0] cannot be reached.
     * GREEN after 163-04.
     */
    public function testExportCertificatesAreOwnDataFullCredential(): void {
        $svc = $this->makeService([$this->makeCertificate()]);
        $result = $svc->exportForUser(self::USER);

        $this->assertNotEmpty($result['certificates'],
            'certificates block must contain the caller\'s own certificate');

        $entry = $result['certificates'][0];
        $this->assertSame(self::VERIFICATION_ID, $entry['verification_id'],
            'verification_id must match the issued certificate');
        $this->assertSame(self::CREDENTIAL_JWT, $entry['credential_jwt'],
            'credential_jwt must be the raw full VC-JWT — no pseudonymisation for own-data export');
        $this->assertSame(self::COURSE_ID, $entry['course_id'],
            'course_id must be preserved in the export');
        $this->assertSame(self::ISSUED_AT, $entry['issued_at'],
            'issued_at timestamp must be preserved');
    }
}
